name: "Release container to staging"
on:
  push:
    branches:
      - main
jobs:
  backend:
    runs-on: ubuntu-latest
    environment: staging
    name: "build"
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN}}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Add poetry export command
        run: poetry self add poetry-plugin-export

      - name: Run Build script
        run: sh ./build.sh

      - name: Build and push image to GHCR
        env:
          IMAGE_TAG: latest
          GHCR_REPOSITORY: ghcr.io/${{ github.repository }}
        run: |
          docker build -f ./Dockerfile -t $GHCR_REPOSITORY:$IMAGE_TAG .
          docker push $GHCR_REPOSITORY:$IMAGE_TAG
